### ISSUE TITLE
output PED

### ISSUE THREAD

**Issue by hmkim** [nicolazzie/AffyPipe#2]
The PED file is a white-space (space or tab) delimited file: the first six columns are mandatory:
     Family ID
     Individual ID
     Paternal ID
     Maternal ID
     Sex (1=male; 2=female; other=unknown)
     Phenotype

from. http://pngu.mgh.harvard.edu/~purcell/plink/data.shtml

If you want to have an 6 columns in AffyPipe output ped file.
Modify this line in below. (suppose.. All samples are non-related;no family)

file_ped.write('FAM '+allids[j]+' 0 0 0 0 '+' '.join(G[j])+'\n')
=>
file_ped.write(allids[j]+' '+allids[j]+' 0 0 0 0 '+' '.join(G[j])+'\n')

**Comment by nicolazzie** [comment]
Dear hmkim,
actually this was intentional. Since variable allids is the "official" (e.g. filename) name of the samples, if researchers need to adjust family or individuals ID, they should use the "--update-ids" PLINK feature ( http://pngu.mgh.harvard.edu/~purcell/plink/dataman.shtml#updatefam).
Either choice (all related / all unrealted) is highly dependent on the samples each user has genotyped. We prefer letting users tailor their final files using innate PLINK solutions.

In any case, thanks for your suggestion!
Ezequiel
